# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b67deeb7fd89e5c0a9ab44947791788fecee1038aa4badc5a4b7d6bbc2d467efc2fa9e9ae0578fb3f1e50dc2db0823525b3bb97d947ed08006921d3ec2b73169

test:
  secret_key_base: 7d65320efffa7ca2ce594e0eaaed62ad14ef04b1aded0bc60ac3771b687919006211dc4154f5537fb7a4829bec8caea76952e800fe014e88773809ed8c3d742f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
